import Head from 'next/head'
import Link from 'next/link'

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + '- Tokoku' : 'Tokoku'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          <nav className='flex h-12 px-4 justify-between shadow-md items-center'>
            <Link href="/">
              <h1 className='text-lg font-bold'>Tokoku</h1>
            </Link>
            <div>
              <Link href="/cart">
                <span className='p-2'>Cart</span>
              </Link>
              <Link href="/login">
                <span className='p-2'>Login</span>
              </Link>
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>
          {children}
        </main>
        <footer className='flex h-10 justify-center items-center shadow-inner'>
          <p>Copyright &copy; 2022 Muhammad Naufal Farras</p>
        </footer>
      </div>
    </>
  )
}
