const data = {
  products: [
    {
      id: 1,
      name: 'Short Shirt',
      slug: 'short-shirt',
      category: 'Shirt',
      image: 'https://source.unsplash.com/random/600x600/?shirt,short',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 25,
      description: 'A new shirt',
    },
    {
      id: 2,
      name: 'Long Shirt',
      slug: 'long-shirt',
      category: 'Shirt',
      image: 'https://source.unsplash.com/random/600x600/?shirt,long',
      price: 80,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 10,
      countInStock: 35,
      description: 'A new long shirt',
    },
    {
      id: 3,
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirt',
      image: 'https://source.unsplash.com/random/600x600/?shirt,slim',
      price: 75,
      brand: 'Puma',
      rating: 4.8,
      numReviews: 30,
      countInStock: 30,
      description: 'A new brand shirt',
    },
    {
      id: 4,
      name: 'Long Slim Shirt',
      slug: 'long-slim-shirt',
      category: 'Shirt',
      image: 'https://source.unsplash.com/random/600x600/?shirt,long',
      price: 85,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 12,
      countInStock: 15,
      description: 'A new long slim shirt',
    },
    {
      id: 5,
      name: 'Short Shirt',
      slug: 'short-shirt',
      category: 'Shirt',
      image: 'https://source.unsplash.com/random/600x600/?shirt,short',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 25,
      description: 'A new shirt',
    },
    {
      id: 6,
      name: 'Long Shirt',
      slug: 'long-shirt',
      category: 'Shirt',
      image: 'https://source.unsplash.com/random/600x600/?shirt,long',
      price: 80,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 10,
      countInStock: 35,
      description: 'A new long shirt',
    },
  ],
};

export default data;
